### ISSUE TITLE
Strict proposal enforcements

### ISSUE THREAD

**Issue by BenjaminPatch** [gnosis/dao-module#18]
### Motivation
Certain proposals require all function calls are executed within one transaction to achieve atomicity. This is currently achievable by using a wrapper contract, but it is not currently enforced on a proposal at the module level.

Another desired enforcement is that of call vs. delegateCall. The effect of a proposal can differ with different operations. Once a proposal passes, there is nothing dictating which of the two can be used to execute a proposal.

### Solution
- Add a way of tracking whether atomic execution is enforced on a given proposal
- Add a function to call all transactions within a proposal (will require using ABIEncoderV2)
- Add a variable to set whether call or delegateCall should be used to execute a proposal.

I have been playing with this on my fork and am happy to do the changes properly, but I was informed that the main repo is not yet configured for external contributions, so I won't push forward with PR-ready changes just yet.

**Comment by rmeissner** [comment]
To enforce atomic execution you would use a [multisend](https://docs.gnosis.io/safe/docs/contracts_details/#multisendsol) that contains your atomic transactions as a single transaction. The only use case where you would want to use multiple transactions is to spread them over multiple blocks. (We should probably add this to the readme).

As your proposal contains a hash of the hashes of all tx that should be executed and the hash of a tx contains the operation (call or delegatecall) there is a strict enforcement on what operation is valid to be used.

**Comment by BenjaminPatch** [comment]
To confirm my understanding, would the appropriate method for this use case be to make a proposal that executes `Multisend.multiSend`?

**Comment by rmeissner** [comment]
You can find an example how to build multisend calls in the safe contract tests: https://github.com/gnosis/safe-contracts/blob/bace2dadf7e0675cec5c5c5d29e3fcb0adb6d31f/test/utils/multisend.ts#L18

We will improve the documentation around that and are working on a sdk that should make this easier.
