### ISSUE TITLE
Add minimum bond

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/dao-module#33]
The latest version of Reality.eth allows the question asker to require a minimum bond.
Making use of this would reduce our monitoring requirements.

https://github.com/RealityETH/monorepo/tree/feature-v3-audit/packages/contracts

**Comment by auryn-macmillan** [comment]
From Edmund
> One thing to watch for is that the way question IDs are calculated changes (as it will now add min_bond to the hash, and also the address of the reality.eth contract to prevent collisions), so if you're calculating on the client side rather than waiting to see what the contract returns it'll need updating.

**Comment by rmeissner** [comment]
See https://github.com/RealityETH/monorepo/blob/feature-v3-audit/packages/contracts/development/contracts/RealityETH-3.0.sol#L301
